### PR TITLE
Support multiple group

### PR DESCRIPTION
**Pull request by khanhhc12**
SubsetExport_Group: Group1,Group2

### CODE REVIEW

**Comment by lukeIam** [comment]
Hi @khanhhc12,

thanks for your contribution!
During testing I found and fixed a little problem: If a entry is selected twice, it would be copied twice to the target db, resulting uuid-conflict.
Also I added a test case for multi group and another for multi tag.

**Comment by lukeIam** [comment]
And ignore the failing Azure DevOps build - this is the first PR thats not from me - I have to adjust the pipline to also run with limited permissions.

**Comment by bmcdonnell** [comment]
Suggestion: document this option in `README.md`. Also explain there that the delimiter (`,`) must not appear in the name of any group or tag that is to be exported.

I think it's probably not worth making the delimiter configurable, or having a way to escape it in the list, but I'm mentioning it in case you think otherwise.

**Comment by bmcdonnell** [comment]
@lukeIam merged without mention in the README?

**Comment by lukeIam** [comment]
> @lukeIam merged without mention in the README?

Thanks for having a look on it - forgot to add the readme change.
Will follow in a minute...

**Pull request merged**
