### PR TITLE
Argon2 support

### LINKED ISSUE #20: Support Argon2 settings if set in source database
Hi,

Many thanks for your great tool. However, it should be nice if you can preserve the encryption settings of source base, mainly if Argon2 is set

Best regards

### PR DESCRIPTION
**Pull request by lukeIam**
+ copy kdf settings from source to target db
+ some fixes and new test cases

closes #20

### CODE REVIEW

**Comment by lukeIam** [comment]
At the moment we are coping all kdf settings from source to target db (some of them can overwritten with an entry).

But does this make sense? This would also copy seed values...
And if not which parameters should be copied and which not?

**AesKdf**:

- [x] ParamRounds
- [ ] ParamSeed

**Argon2Kdf**:

- [ ] ParamSalt
- [x] ParamParallelism
- [x] ParamMemory
- [x] ParamIterations
- [ ] ParamVersion
- [ ] ParamSecretKey
- [ ] ParamAssocData

@bmcdonnell @wellread1 @PhilZ-cwm6

**Comment by wellread1** [comment]
My two cents:

I think it would be a good idea to follow the lead of Dominik, the KeePass developer.  Copy parameters in contexts where KeePass copies them, and generate new parameters in contexts where KeePass generates new values.

I am a user, not a cryptographer, developer, or programmer but I believe that there is a rationale for generating a new salt for key hashing whenever the user secret (i.e. database master key) or hashing input parameters are changed.  However, it may not be desirable to generate new salt when nothing has changed.

If you can't confirm the copy behavior of KeePass in the relevant contexts (e.g. after a change to database security settings, when saving a database or when exporting) I suggest you ask the KeePass developer about best practices.

-----------

I notice that you might be removing the limit for argon parallelism? (I don't read code so I can't be certain.) 

It may be counterproductive to allow a degree of parallelism greater than the number of concurrent threads that a user's device is capable of using. Excessive parallelism may cede an advantage to an attacker that has accesses to highly parallel hardware.

Again I recommend that you query the developer regarding the reasoning behind limits he has imposed on the Argon2 algorithm.

**Comment by lukeIam** [comment]
> I think it would be a good idea to follow the lead of Dominik, the KeePass developer. Copy parameters in contexts where KeePass reuses them, and generate new parameters in contexts where KeePass generates new values.

As far as I could figure out: KeePass is only exporting with AES-Parameters. And there they are keeping the Seed. (In my opinion it should be changed)

> If you can't confirm the copy behavior of KeePass in the relevant contexts (e.g. after a change to database security settings, when saving a database or when exporting) I suggest you ask the KeePass developer about best practices.

I will - better play it safe with such things...

> I notice that you might be removing the limit for argon parallelism? (I don't read code so I can't be certain.)
> 
> It may be counterproductive to allow a degree of parallelism greater than the number of concurrent threads that a user's device is capable of using. Excessive parallelism may cede an advantage to an attacker that has access to highly parallel hardware.

Yes - I removed the limit. At the beginning I did the same mistake. But after reading the documentation of Argon2 I figured out that higher numbers increases the complexity. As the default ist 2 - I removed the limit.

**Comment by lukeIam** [comment]
Question on sourceforge: 
https://sourceforge.net/p/keepass/discussion/329220/thread/6976c05f/#96f7

**Comment by lukeIam** [comment]
> Question on sourceforge:
> https://sourceforge.net/p/keepass/discussion/329220/thread/6976c05f/#96f7

ok - we just copy everything and `KdbxFile.Save()` calls `kdf.Randomize()` which randomizes the seeds.

**Comment by wellread1** [comment]
>ok - we just copy everything and KdbxFile.Save() calls kdf.Randomize() which randomizes the seeds.

Sounds good.

>Yes - I removed the limit. At the beginning I did the same mistake. But after reading the documentation of Argon2 I figured out that higher numbers increases the complexity. As the default ist 2 - I removed the limit.

I do not believe that the statement and recommendations in [Argon2: the memory-hard function for password hashing and other applications](https://password-hashing.net/argon2-specs.pdf) by alex.biryukov et al. are consistent with the conclusion that higher degrees of parallelism increase complexity or that complexity per se is desirable.

See section **6.2 Implementing parallelism**

"The simplest way to use p parallel cores...admits a trivial tradeoff: an  adversary  just  makes ...sequential  calls...which  keeps  the  time-area product constant".  The authors proceed to implement a solution that resists that attack.  However, it does not follow that because the chosen parallelism implementation was more complex, that increasing parallelism increases complexity or that complexity per se is a figure of merit.

In other sections of the white paper, the authors make statements to the effect that the optimum degree of parallelism is a relatively small value that is proportional to the available CPU cores.

See sections:

**4.1 Available features**

"Parallelism. Argon2 may use up to 224 threads in parallel, although in our experiments 8 threads already exhaust the available bandwidth and computing power of the machine"


**6.4 User-controlled parameters**
"Degree d of parallelism. This number determines the number of threads used by an optimized implementation of Argon2. We expect that the user is restricted by a number of CPU cores (or half-cores) that can be devoted to the hash function, and chooses d accordingly (double the number of cores)." 

**9 Recommended parameters**

"2. Figure out the maximum number h of threads that can be initiated by each call to Argon2."

6.4 and 9 are recommendations that the optimum value for a particular device will likely be the "double the number of cores"  

-------------

At any rate, I think the limit can be removed if the plugin documentation provides some guidance e.g. "Typical parallelism values should be less than or equal to two times the number of available processor cores.  If increasing parallelism does not improve performance then parallelism should be reduced."

**Comment by wellread1** [comment]
> so its harder to attack a 4-thread-hash with 2 threads than a 2-thread-hash, right?

Correct, but the question is framed wrong.  The salient question is

->It is harder for whom to a calculate a 4-thread Argon2 function?

We should assume the user has the limited resources (e.g. a 2 or 4 core CPU) and the attacker is using a highly parallel and optimized computing architecture (e.g. 18 core 36 thread CPU).

>Why should it be less [than] the available logical cores?

In an ideal situation, the user should take advantage of the full resources (all cores) to calculate the encryption key, but in practice that may not always be desirable, e.g. the computer is used for other things.  I believe the table you posted is overall time to calculate the encryption key as a function of parallelism on an 8 core machine. The table illustrates diminishing performance gains that are approaching 0 as the degree of parallelism is increased.

If the user does not make full use of the performance gains available through increasing parallelism the user can still reach the desired work factor by adjusting the other parameters, especially memory resources.  What they mustn't do, is increase parallelism to values that yield little or no performance benefit on the machine that they use to calculate Argon2.

**Comment by lukeIam** [comment]
> If the user does not make full use of the performance gains available through increasing parallelism the user can still reach the desired work factor by adjusting the other parameters, especially memory resources. What they mustn't do, is increase parallelism to values that yield little or no performance benefit on the machine that they use to calculate Argon2.

ok - I think I got what you mean:
Setting parallelism higher than the available cores (physical or by other workload) does not make sense as the user needs more time to compute the key (results in configuring less rounds) and an attacker with enough cores can fully use the too high parallelism setting.

**Comment by wellread1** [comment]
I think that is about right.  Though I can usually achieve my target Argon2 key transformation time (e.g. 1 sec) by optimizing parallelism and memory parameters @ 1 iteration.

**Pull request merged**
