### PR TITLE
Copy icon if ExportUserAndPassOnly set to true

### PR DESCRIPTION
**Pull request by lukeIam**
as requested here: https://github.com/lukeIam/KeePassSubsetExport/issues/24#issuecomment-932097787

### CODE REVIEW

**Comment by aflexus** [comment]
Hi, lukelam!
Are there any chance to test the version with this change?

**Comment by lukeIam** [comment]
> Hi, lukelam! Are there any chance to test the version with this change?

https://lukeiam.visualstudio.com/65ae3512-9e36-4185-b514-aeac74a21017/_apis/build/builds/116/artifacts?artifactName=PGLX-Version&api-version=7.0&%24format=zip

from

https://lukeiam.visualstudio.com/KeePassSubsetExport/_build/results?buildId=116&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by aflexus** [comment]
> > Hi, lukelam! Are there any chance to test the version with this change?
> 
> https://lukeiam.visualstudio.com/65ae3512-9e36-4185-b514-aeac74a21017/_apis/build/builds/116/artifacts?artifactName=PGLX-Version&api-version=7.0&%24format=zip
> 
> from
> 
> https://lukeiam.visualstudio.com/KeePassSubsetExport/_build/results?buildId=116&view=artifacts&pathAsName=false&type=publishedArtifacts

All works pretty fine. Thank you a lot!

**Pull request merged**
