### PR TITLE
Ref support and option for user pass only

### PR DESCRIPTION
**Pull request by lukeIam**
This is basically PR #34 from @Angelelz but without the pglx file in the history.

Also I've did some small modifications in a separate commit.

### CODE REVIEW

**Comment by lukeIam** [comment]
@Angelelz I changed the ref resolver logic a bit: As password fields are going through this function I don't want to same the content in a normal string.

But SprEngine seems to only support string -> I've used ProtectedString and check first if it's really a reference string. If so we decode it to a string, if not we return the ProtectedString directly.

**Comment by lukeIam** [comment]
@Angelelz 

Two questions:

- should we rename the UsernamePassOnly option? It's exporting more than that (e.g. url)
- we should write tests for the newly added features (do you like to add some or should I do it when I find time for it)

**Comment by lukeIam** [comment]
closes #29 and maybe helps #24

**Comment by Angelelz** [comment]
I think the name should be changed but can't think of anything short and related. Maybe NoStringFields? but also notes and attachments are not being copied. I leave that to you.
About the tests, I actually don't know how those works, I didn't use them, I tested everything manually. I will try to understand them and if I come up with something before you, will post the PR

**Comment by Angelelz** [comment]
Hello Again, I want to start contributing again. First I think the option UserAndPassOnly should be renamed to RestrictedFieldExport or LimitedFieldExport, I'll wait for your answer to implement it.

Also, I will start working on some tests, to be honest I didn't do it before because I did not know about nuget packages and how I needed to check them to resolve some references in that solution. Anyway, some commits on the way!

BTW, great idea to convert the field into a Byte array in the GetFieldWRef method, to be compared safely with RefStringByteArray and then delete the Byte array, that way the field only gets converted into a string only if absolutely necessary.

**Comment by Angelelz** [comment]
I would like you to take a look a [my implementation](https://github.com/Angelelz/KeePassMasterSlaveSync/blob/SaferRefResolvement/KeePassMasterSlaveSync/Settings.cs) of GetFieldWRef method with no need for SprEngine. It's working on my plugin descendent from this one. It's using your idea of comparing first if the field actually contains a reference with a byte array. Maybe we could use it here.

**Comment by Angelelz** [comment]
Nevermind that! Please check [Dominik Reichl response](https://sourceforge.net/p/keepass/discussion/329221/thread/fce93e24ac/#bec5) to my question about my new and shiny and totally not good GetFieldWRef method. :)

**Comment by lukeIam** [comment]
@Angelelz sorry that it took soo long... 😟

**Pull request merged**
