### PR TITLE
Override entire group

### PR DESCRIPTION
**Pull request by Angelelz**
I implemented a way to override an entire group in an export job. I use KeePassSubsetExport to share some items with my wife. I wanted to be able to share items and delete them when necessary by deleting them in my database and propagating that deletion to the shared file (since that file is in a shared Gdrive folder).

### CODE REVIEW

**Comment by Angelelz** [comment]
This is the first time I'm trying to contribute to a project, and there is clearly something wrong with my pull request. But my offline build of this branch is working as expected. Care to explain what I'm missing? Thanks

**Comment by lukeIam** [comment]
Hi @Angelelz thanks for your contribution!
The failing builds are my fault: I haven't found a safe way to build PR from others without compromising secrets. I will try to fix that in the future - for now just ignore them.

Sorry I'm a bit in stressed before holiday but I will try to review you code before I leave.

**Comment by lukeIam** [comment]
Hi @Angelelz,

thanks again for you contribution! 
I had a closer look and refactored a small thing: with your code it could be that the plugin tries to delete the same group multiple times (if multiple entries are in the same group - correct me if I'm wrong). I just changed the code to collect all groups and apply a Distinct() on it.

And I'm unsure about the warning in [Exporter.cs:528](https://github.com/lukeIam/KeePassSubsetExport/pull/31/files#diff-c9f93562b92e19281815f8a7adc16486R528): I will appear if the target group is not there and can't be deleted because it was deleted, this is the first export, ... .
But whats the difference for the user? If it's there we will delete it, if it's not there also fine 😉

**Comment by Angelelz** [comment]
I'm sorry about all the non optimal code, as I said, I'm literally learning my way into writing this stuff, I'm just learning about linq and all those methods like Distinct(). Also, English is not my native language, which explain all the typos 🤣

And yes, you are probably right, that 'else' could be commented out or deleted! It is not necessary.

**Comment by lukeIam** [comment]
> I'm sorry about all the non optimal code, as I said, I'm literally learning my way into writing this stuff, I'm just learning about linq and all those methods like Distinct().

no worries - I happy about every contribution 😃 (and in this case the optimization was quite small).

> English is not my native language

Meine neither and there will be other typos somewhere hiding in the project.

> And yes, you are probably right, that 'else' could be commented out or deleted! It is not necessary.

I will delete the else clause.

One last important thing: Please do NOT mix different changes/PRs. Looks like your last commit merged something from the ref-PR. I like to keep it with one new feature per PR.
Is is ok for you if I revert your OverrideEntireGroup brach to the state before? 
Then this PR would be ready to go through automatic testing (I hope I had success fixing it) and to be merged after. (I will review the other PRs separately)

**Comment by lukeIam** [comment]
@Angelelz just saw that you have added a pglx file to the repo - please do not add derived binary files to the repo -> those files will be in the history forever and are stored fully on each change.
If you want to provide compiled version upload it e.g. to a github comment.

(I will rewrite the history to remove the pglx file before merging this - note that will change all your commits since then in this branch)

**Comment by Angelelz** [comment]
Of course I'm ok with your changes, I just don't know how to do many of this stuff, and the mistakes you mention are because I just don't know the right way.
If I understand correctly, for every feature I should create a new branch from master and work on that? I did not know that when I did it, mostly because I wanted my build to have all those changes I was making

**Comment by lukeIam** [comment]
> Of course I'm ok with your changes

So I removed your last merge in this branch.

> you mention are because I just don't know the right way.

no problem ...

> If I understand correctly, for every feature I should create a new branch from master and work on that?

Correct

> I wanted my build to have all those changes I was making
No problem - just make an other branch 

triggering build:
/AzurePipelines run

**Pull request merged**
